import type { Metadata } from "next";

import { address, shop } from "./config.ts";

/* One shape for every page's Open Graph block.
 *
 * Next inherits the whole `openGraph` object from the layout when a page does
 * not declare one, and *replaces* it wholesale when a page does. Both halves
 * of that bit us, in opposite directions, and the stage-3 SEO audit found each
 * one:
 *
 *  - `/urunler`, `/galeri`, `/hizmetler`, `/hakkimizda` and `/iletisim`
 *    declared no openGraph, so they inherited the layout's — including
 *    `url: shop.url`. Every one of them told a platform it *was* the homepage,
 *    while its canonical said otherwise. A share of /hakkimizda previewed as
 *    the front page.
 *  - The category pages declared their own and so lost `siteName` and
 *    `locale: "tr_TR"`, which nothing had put back.
 *
 * A helper cannot be inherited wrongly. `url` is always present and always the
 * page's own; site-level fields come along for free.
 *
 * Note the layout deliberately does NOT set `url` — see app/layout.tsx. Pages
 * that must not be indexed (/yol-tarifi, the 404) then inherit no URL at all,
 * which is better than inheriting the homepage's.
 */
/* The site-wide card, used by every page that does not name its own. Only the
 * four category pages do.
 *
 * Generated by `npm run og` from the layouts in app/dev/og, and committed —
 * see scripts/og.mjs for why they are not built at build time. If this URL
 * 404s, that script has not been run.
 *
 * The alt text sits here rather than in an app/opengraph-image.alt.txt sidecar
 * because the file convention it belonged to is gone; the reasoning is in
 * scripts/og.mjs. */
const DEFAULT_CARD = {
  url: "/og/default.png",
  width: 1200,
  height: 630,
  alt: `${shop.name} — ${address.locality}, ${address.region}. Ata Lirası ve dükkânın adı.`,
} as const;

export function openGraph(
  path: string,
  extra?: Omit<NonNullable<Metadata["openGraph"]>, "url">,
): Metadata["openGraph"] {
  return {
    type: "website",
    locale: "tr_TR",
    siteName: shop.name,
    url: `${shop.url}${path}`,
    /* Always an image. A page that declares openGraph and forgets this one
       field previews blank, and nothing about the page looks wrong until
       somebody shares it. `extra` can override it — the categories do. */
    images: [DEFAULT_CARD],
    ...extra,
  };
}
